export let etsyTypesMap = {
    "string": "string",
    "int": "number",
    "epoch": "number",
    "float": "number",
    "boolean": "boolean",
    "user_id_or_name": "string | number",
    "shop_id_or_name": "string | number",
    "team_id_or_name": "string | number",
    "treasury_description": "string",
    "treasury_id": "string",
    "treasury_search_string": "string",
    "treasury_title": "string",
    "enum(values)": null as any,
    "array(type)": null as any,
    "map(keyType,valueType)": null as any,
    "color_triplet": "string",
    "color_wiggle": "number",
    "latitude": "number",
    "longitude": "number",
    "image": "string",
    "region": "string",
    "currency": "string",
    "language": "string",
    "category": "string",
    "taxonomy": "any",
    "listing_variation": "any",
    "featured_rank": "number",
    "cart_id": "string | number",
    "text": "string"
};
